### ISSUE TITLE
configuration/http_conn_man/headers.md

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/envoy#13]

**Comment by yatwql** [comment]
我想翻译这章,不过git上的Markdown文稿对比原文有非常大的缺失

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers

**Comment by skyao** [comment]
@yatwql 原文太长，我们没有完全搬上去。你翻译的时候按照原文来翻译好了，只是需要辛苦一下将格式调整为markdown，我们最后提交的都是markdown文件。谢谢

**Comment by skyao** [comment]
@yatwql 这篇就assign给你啦，我已经将label设置为 translating，避免其他人重复翻译。你可以在群内联系净超，加入组织，就可以自己assign和直接提交。

**Comment by rootsongjc** [comment]
@yatwql 我已经邀请你加入该 GitHub 组织了，请检查你的邮箱是否收到邀请。

**Comment by skyao** [comment]
@yatwql 这篇就assign给你啦，我已经将label设置为 translating，避免其他人重复翻译。你可以在群内联系净超，加入组织，就可以自己assign和直接提交。

**Comment by yatwql** [comment]
@rootsongjc  已收到并加入,但还是没权限assign给自己

**Comment by yatwql** [comment]
@rootsongjc 可否提点一下如何将源站的rst格式转换为markdown，我想偷个懒将源站的源文件转为markdown后再翻译，用了例如 `pandoc -s -f rst -t markdown -o headers.md headers.rst.txt ` 还是没什么效果

**Comment by rootsongjc** [comment]
pandoc命令我也试过，没什么效果，我是打开html页面后手动复制到typra中的，能够很好的保持markdown格式。
