### ISSUE TITLE
about_docs.md translation improvements

### ISSUE THREAD

**Issue by cockroachdbcn** [servicemesher/envoy#249]
## 基本信息

译文地址：

https://github.com/servicemesher/envoy/blob/master/about_docs.md

原文地址：

https://www.envoyproxy.io/docs/envoy/latest/about_docs

## Issue 类型

请从下方选择提交的 Issue 类型，以便管理员为 Issue 设置标签。

- [ ] Typo：格式、语法、错字、遗漏、翻译错误
- [X] Enhancement：翻译正确但是原文表达不清，需要为原文增加解释说明
- [ ] Update：原文有更新需要同步翻译

添加完 Issue 后就可以提交 PR了。

## 建议

如果上述类型都不符合你的要求，或者对某篇文章中的翻译有疑义，请在下方指出。

**Comment by rootsongjc** [comment]
@cockroachdbcn 没有相应的 PR 来解决这个 issue 吗？
