### ISSUE TITLE
Protobuf 建议不译成协议缓冲区而是保留英文名

### ISSUE THREAD

**Issue by zhengbuqian** [servicemesher/envoy#266]
## 基本信息

译文地址：http://www.servicemesher.com/envoy/intro/arch_overview/grpc.html#

原文地址：https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/grpc

## Issue 类型

请从下方选择提交的 Issue 类型，以便管理员为 Issue 设置标签。

- [ ] Typo：格式、语法、错字、遗漏、翻译错误
- [x] Enhancement：翻译正确但是原文表达不清，需要为原文增加解释说明
- [ ] Update：原文有更新需要同步翻译

添加完 Issue 后就可以提交 PR了。

## 建议

第一句中的protocol buffers指的是Google的[Protocol Buffers](https://developers.google.com/protocol-buffers/)序列化/反序列化框架，建议不翻译。

**Comment by rootsongjc** [comment]
@zhengbuqian 感谢您的建议，可以直接提交 PR 修改 Protobuf 的翻译。

**Comment by rootsongjc** [comment]
本项目已不再维护，请参与https://i.cloudnative.to/envoy/1.16-translation/translation-process
