### ISSUE TITLE
configuration/cluster_manager/cluster_circuit_breakers.md

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/envoy#5]

**Comment by fleeto** [comment]
原文：[https://github.com/servicemesher/envoy/tree/master/configuration/cluster_manager/cluster_circuit_breakers.md](https://github.com/servicemesher/envoy/tree/master/configuration/cluster_manager/cluster_circuit_breakers.md)

**Comment by lovepoem** [comment]
Clame
