### ISSUE TITLE
install/tools/schema_validator_check_tool.md

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/envoy#70]

**Comment by fleeto** [comment]
原文：[https://github.com/servicemesher/envoy/tree/master/install/tools/schema_validator_check_tool.md](https://github.com/servicemesher/envoy/tree/master/install/tools/schema_validator_check_tool.md)

**Comment by cockroachdbcn** [comment]
认领

**Comment by cockroachdbcn** [comment]
认领
