### ISSUE TITLE
intro/arch_overview/arch_overview.md

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/envoy#72]

**Comment by fleeto** [comment]
原文：[https://github.com/servicemesher/envoy/tree/master/intro/arch_overview/arch_overview.md](https://github.com/servicemesher/envoy/tree/master/intro/arch_overview/arch_overview.md)

**Comment by xieydd** [comment]
认领

**Comment by rootsongjc** [comment]
不好意思，这篇文档是一个导航页面，并没有什么实质内容，本来就没有在gitbook的目录列出，原文档我忘记删除了，这篇实际上不需要翻译。
