### ISSUE TITLE
intro/arch_overview/http_filters.md

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/envoy#84]

**Comment by fleeto** [comment]
原文：[https://github.com/servicemesher/envoy/tree/master/intro/arch_overview/http_filters.md](https://github.com/servicemesher/envoy/tree/master/intro/arch_overview/http_filters.md)

**Comment by yatwql** [comment]
认领

**Comment by yatwql** [comment]
@rootsongjc PR已经merge，应可关闭该issue
